baseurl: /

# Build settings

markdown: kramdown
permalink: pretty

port: 8000

Обо мне: '/about'
exclude: ['the_design.psd']

sass:
  sass_dir: assets/_sass
  style: nested
  
gems:
  - jekyll-compass